services:
  stellar_journal:
    build:
      context: "../stellar_journal"
      dockerfile: Dockerfile
    restart: always
    hostname: stellar_journal
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
    networks:
      - net

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

volumes:
  postgres_data:

networks:
  net:
    external: true