version: '3.8'

services:
  stellar_journal:
    container_name: stellar_journal
    build:
      context: "../stellar_journal"
      dockerfile: Dockerfile
    restart: always
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8123:${APP_PORT}"
    networks:
      - net

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    hostname: postgresql

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  net:
